version: '3'

services:
    webserver:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/php/:/code
            - ./:/opt/project
        links:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./docker/php/:/code
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/loca/etc/php/conf.d/error-reporting.ini
            - ./:/opt/project
