version: '3'

services:
    webserver:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        links:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./docker/php/:/var/www/html
